import { DeployGuardState } from "../state/deployGuardState";

export const outputFormatterAgent = async (
  state: DeployGuardState
): Promise<Partial<DeployGuardState>> => {
  const riskEmoji =
    state.risk_level === "HIGH"
      ? "🔴"
      : state.risk_level === "MEDIUM"
      ? "🟡"
      : "🟢";

  const comment = `
## 🛡 DeployGuard Pre-CI Report

**PR:** #${state.pr_number} — ${state.pr_title}
**Author:** @${state.author}
**Risk Score:** ${state.risk_score}/100 ${riskEmoji} **${state.risk_level}**

---

### 📊 Risk Breakdown
| Factor | Score |
|--------|-------|
| Diff Impact | ${state.risk_breakdown["diff"]} |
| Dependency Risk | ${state.risk_breakdown["dependency"]} |
| Migration Risk | ${state.risk_breakdown["migration"]} |
| Critical Path Impact | ${state.risk_breakdown["critical_paths"]} |

---

### 🧠 Strategy Summary
${state.strategy_summary}

**Reasoning:** ${state.strategy_reasoning}

---

### 🚀 Recommended Deployment Plan
${state.deployment_plan.map((s) => `- ${s}`).join("\n")}

---

### ✅ Pre-CI Checks to Add
${state.pre_ci_checks_to_add.map((s) => `- ${s}`).join("\n")}

---

### 🔄 Rollback Preparation
${state.rollback_preparation.map((s) => `- ${s}`).join("\n")}

---

**Confidence:** ${state.strategy_confidence}%
*Generated by DeployGuard — Pre-CI Intelligence*
`.trim();

  return { formatted_comment: comment };
};